### ISSUE TITLE
Not closing all sessions in app.py

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/land-records#110]
Karen noted that the app was down, and I found this error in the server log:

```
ERROR:tornado.access:500 GET //input?q=b (127.0.0.1) 30003.36ms
ERROR:app:Exception on /input [GET]
Traceback (most recent call last):
  File "/apps/land-records/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/apps/land-records/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/apps/land-records/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/land-records/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/land-records/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/apps/land-records/repo/scripts/app.py", line 506, in input
    Base.metadata.create_all(engine)
  File "/apps/land-records/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3352, in create_all
    tables=tables)
  File "/apps/land-records/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1616, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/apps/land-records/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1609, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/apps/land-records/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1799, in contextual_connect
    self.pool.connect(),
  File "/apps/land-records/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 338, in connect
    return _ConnectionFairy._checkout(self)
  File "/apps/land-records/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 641, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/apps/land-records/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/apps/land-records/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 957, in _do_get
    (self.size(), self.overflow(), self._timeout))
TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30
```

Looks to be because some sessions are not closing properly: http://stackoverflow.com/questions/3360951/sql-alchemy-connection-time-out

**Comment by ThomasThoren** [comment]
Added a few `session.close()` lines, notably in the autocomplete POST calls. That could have easily caused problems if the sessions weren't closing properly. I'll keep an eye on this.
